name: Cross-Compile fbDOOM for PowerPC

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build-powerpc:
    runs-on: ubuntu-24.04

    steps:
    - name: Récupérer le code source
      uses: actions/checkout@v4

    - name: Installer la toolchain PowerPC Linux officielle
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-powerpc-linux-gnu make

    - name: Compiler fbDOOM en mode STATIQUE (pour compatibilité vieil Ubuntu)
      run: |
        cd fbdoom
        make clean
        # LDFLAGS="-static" dit au compilateur de ne pas dépendre de la GLIBC du système cible
        make CROSS_COMPILE=powerpc-linux-gnu- NOSDL=1 LDFLAGS="-static -Wl,--gc-sections"

    - name: Sauvegarder l'exécutable compilé (Artifact)
      uses: actions/upload-artifact@v4
      with:
        name: fbdoom-powerpc-binary
        path: fbdoom/fbdoom
