name: Cross-Compile fbDOOM for PowerPC

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch: # Permet de lancer la compilation manuellement d'un clic sur GitHub

jobs:
  build-powerpc:
    runs-on: ubuntu-24.04

    steps:
    - name: Récupérer le code source
      uses: actions/checkout@v4

    - name: Installer la toolchain PowerPC Linux officielle
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-powerpc-linux-gnu make

    - name: Compiler fbDOOM avec les bonnes variables
      run: |
        cd fbdoom
        # On lance make en lui passant directement les variables par injection (plus propre que sed !)
        make clean
        make CROSS_COMPILE=powerpc-linux-gnu- NOSDL=1

    - name: Sauvegarder l'exécutable compilé (Artifact)
      uses: actions/upload-artifact@v4
      with:
        name: fbdoom-powerpc-binary
        path: fbdoom/fbdoom
